### ISSUE TITLE
Can not run speech to text extension locally

### ISSUE THREAD

**Issue by pascalbe-dev** [GoogleCloudPlatform/firebase-extensions#506] opened 2024-05-24 09:04 UTC
### [REQUIRED] Step 2: Describe your configuration

- Extension name: **googlecloud/speech-to-text**
- Extension version: **0.1.5**
- Configuration values (redact info where appropriate):

```env
COLLECTION_PATH=transcriptions
ENABLE_AUTOMATIC_PUNCTUATION=true
EXTENSION_BUCKET=project-stage.appspot.com
LANGUAGE_CODE=de-DE
LOCATION=europe-west3
MODEL=default
```

_I replaced the real project name._

#### Steps to reproduce:

- install the extension locally via `firebase ext:install --local googlecloud/speech-to-text` (set config resulting int he configuration from above)
- enable firestore and firebase storage in the firebase.json

```json
"firestore": {
    "rules": "firestore/firestore.rules",
    "indexes": "firestore/firestore.indexes.json"
  },
  "storage": {
    "rules": "storage/storage.rules"
  },
  "extensions": {
    "speech-to-text": "googlecloud/speech-to-text@0.1.5"
  },
```

- run the emulator via `firebase emulators:start`
- open the emulator UI
- upload an audio file in the emulator storage

##### Expected result

- the extension runs successfully
- the transcribed audio gets put into firestore

##### Actual result

- the extension run fails with the error `Error: 5 NOT_FOUND: No such object: project-stage.appspot.com/tmp/cde16c4b-485c-42a4-8a18-006a17234fad/audiofile.m4a.wav`

### My thoughts

- it seems like the speech API (running in the real gcloud project) is called in a way, that it tries to access the audio file from the real storage
- but the file is only in the emulator storage

-> how can I get it working with my storage locally?

**Comment by pr-Mais** [comment] 2024-05-27 16:41
Thanks for reporting, I can reproduce the issue locally, looking into it!

**Comment by cabljac** [comment] 2024-06-13 14:22
I dont think this is possible, it's blocked as the speech to text API is a long-running operation, which writes to a production bucket.

**Comment by cabljac** [comment] 2024-06-13 14:23
see https://github.com/GoogleCloudPlatform/firebase-extensions/issues/299 for example

**Comment by pascalbe-dev** [comment] 2024-06-14 07:36
I see. If that's how it is, then it's a pity. Would be great to really work with the extension also locally. 

Keeping this one open. Let me know, if you do for sure not plan to change it. Then we could close it.

**Comment by cabljac** [comment] 2024-06-18 08:26
I think let's close this as it's essentially a duplicate of #299 

I think we can do something here, but unfortunately it won't be changed in the near future. I'm open to suggestions/a PR though :)  I don't know how we'd get around the long-running operation though

**Comment by cabljac** [comment] 2024-06-18 08:27
closing as dupe of #299

**Closed by cabljac** 2024-06-18 08:27 UTC
Labels: type: bug, blocked, extension: speech-to-text

**Comment by Juraj333** [comment] 2024-06-18 10:10
Ahoj bro, Please remind me what I annoyed you with? I already have chaos in

Dňa ut 18. 6. 2024, 10:27 Jacob Cable ***@***.***> napísal(a):
