### ISSUE TITLE
[firestore-genai-chatbot] ClientError 400 Bad Request using standard config

### ISSUE THREAD

**Issue by jakobbjelver** [GoogleCloudPlatform/firebase-extensions#348] opened 2024-01-27 14:51 UTC
### Configuration

- Extension name: **firestore-genai-chatbot**
- Extension version: **0.0.5**
- Configuration values (from cloud functions variables):
CANDIDATE_COUNT 1
CANDIDATES_FIELD candidates
COLLECTION_NAME users/{uid}/discussions/{discussionId}/messages
DATABASE_INSTANCE
DATABASE_URL
ENABLE_DISCUSSION_OPTION_OVERRIDES no
EXT_INSTANCE_ID firestore-genai-chatbot
FIREBASE_CONFIG {"projectId":"my_app","databaseURL":"","storageBucket":"my_app.appspot.com"}
GCLOUD_PROJECT my_app
GENERATIVE_AI_PROVIDER vertex-ai
LOCATION us-central1
MODEL gemini-pro
PROJECT_ID my_app
PROMPT_FIELD prompt
RESPONSE_FIELD response
STORAGE_BUCKET my_app.appspot.com

#### Steps to reproduce:

This happens whenever I request the extension. I can successfully insert and retrieve values from the Firestore database, but it will return an 'ERRORED' state with message 'An error occurred while processing the provided message, Failed to generate response, see function logs for more details'. 

So, when I then see the cloud function logs, this is what I get: 
"ClientError: [VertexAI.ClientError]: got status: 400 Bad Request
    at throwErrorIfNotOK (/workspace/node_modules/@google-cloud/vertexai/build/src/index.js:395:15)
    at GenerativeModel.generateContentStream (/workspace/node_modules/@google-cloud/vertexai/build/src/index.js:321:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async VertexDiscussionClient.generateResponse (/workspace/lib/generative-client/vertex_ai.js:53:36)
    at async VertexDiscussionClient.send (/workspace/lib/generative-client/base_class.js:26:16)
    at async FirestoreOnWriteProcessor.generateChatResponse [as processFn] (/workspace/lib/generate_chat_response.js:23:20)
    at async FirestoreOnWriteProcessor.run (/workspace/lib/firestore-onwrite-processor/index.js:83:28) {
  stack_trace: undefined
}"

Therefore I have identified the 400 error, but I cannot understand why. My config (the setup made in the Firebase console) is standard, but my own guess is that I am missing something that makes the request to the Generative Language API in the @googlecloud/vertextai package fail. 

I have tried different configurations and nothing seems to work. Having europe-west1 as the LOCATION config parameter will result in a 404 Not Found. Could this be a location issue as I myself is based in Europe? Whenever I am deploying to US locations I get the 400 error. 

Another notable thing is that out of maybe 100 tries, I have successfully retrieved maybe 10 responses or so with varying consistency (sometimes 5 in a row, and sometimes randomly).

Also, I cannot find any generated Secrets in the Secrets Manager. I am guessing that this is because I am using the vertex-ai and not google-ai as the Gemini API Provider. 

I could not find anything helpful in logs, documentation or on forums. Even inspecting the vertex-ai package source code gave me nothing more than a reference to what the 400 error would mean. I know the error in question is rooted in the vertex-ai package, but I am guessing that it is the extension that won't provide the correct config values (like location, API key, project ID, etc.).

I apologize for any inconsistencies in my bug report as this is my first one ever, and I am quite new to programming. Any help or leads on this will be greatly appreciated!

Thanks in advance

**Comment by jakobbjelver** [comment] 2024-01-28 11:46
**UPDATE** I got it to work! While debugging the extension I found that the environment variables did not get passed to the config properly. I do not know if this is on purpose, but the final config object passed to the Generative Language API was empty. 

To fix it, I reinstalled the extension and entered values into Temperature, Nucleus sampling probability, Context and Sampling strategy parameter, (instead of leaving them empty and falling back on default). Also, I changed the location to us-central1. I am unable to say which of these changes made it work, of if it was in combination, but it worked. So this probably should be looked into. Perhaps also some extended error handling would be greatly appreciated 👍 

This is my current config (from cloud functions variables): 
```
CANDIDATE_COUNT 1
CANDIDATES_FIELD candidates
COLLECTION_NAME users/{uid}/discussions/{discussionId}/messages
CONTEXT You are an AI assistant
DATABASE_INSTANCE
DATABASE_URL
ENABLE_DISCUSSION_OPTION_OVERRIDES no
EXT_INSTANCE_ID firestore-genai-chatbot
FIREBASE_CONFIG {"projectId":"my_app","databaseURL":"","storageBucket":"my_app.appspot.com"}
GCLOUD_PROJECT my_app
GENERATIVE_AI_PROVIDER vertex-ai
LOCATION us-central1
MODEL gemini-pro
PROJECT_ID my_app
PROMPT_FIELD prompt
RESPONSE_FIELD response
STORAGE_BUCKET my_app.appspot.com
TEMPERATURE 0.3
TOP_K 3
TOP_P 0.5
```

**Comment by cabljac** [comment] 2024-01-29 11:05
Hey! thanks for raising this. lots of points here

- I think some locations are blocked for Gemini, the UK is definitely blocked so it could be that europe-west is blocked. That error does actually give a 400 though, so it cant be the source of your 404.

The reason we chose not to write the actual message into firestore was that the Gemini API had a bug where it was exposing API keys in error logs. That may be fixed now, and I should look into it and update error handling if possible.

I will try and reproduce your original error first, and see if i can figure out the issue :)

**Comment by cabljac** [comment] 2024-01-30 16:57
Hey @jakobbjelver I tried installing with your original parameters and couldn't reproduce the 400 error. It's hard to determine what originally caused the error.

You don't need a secret for Vertex AI by the way, only for Google AI. If you set a secret in the install step, you should still see it though.

**Comment by jakobbjelver** [comment] 2024-02-01 00:10
Hej Jacob!

Sorry for my late response. Thank you a lot for your attention and quick
help.

I do no longer have the error either, which makes it impossible even for me
to reproduce...

I will keep in touch if I encounter it again, and try to define the
parameters better in order for it to be able to be reproduced. Till then
(if it may happen), do you want me to close the issue in Github?

I really like the extension and am enjoying the service, you are doing a
great job.

Thanks and best regards

Den tis 30 jan. 2024 kl 17:57 skrev Jacob Cable ***@***.***>:

**Comment by cabljac** [comment] 2024-02-01 10:13
@jakobbjelver Thanks!

I'll close this issue for now, feel free to open a new one if you get the error again!

**Closed by cabljac** 2024-02-01 10:13 UTC
Labels: type: bug, extension: firestore-genai-chatbot
