### ISSUE TITLE
[speech-to-text] eventarc contains 0 information about what file was processed

### ISSUE THREAD

**Issue by nohe427** [GoogleCloudPlatform/firebase-extensions#107] opened 2023-07-19 19:59 UTC
### [READ] Step 1: Are you in the right place?

Issues filed here should be about a feature request for a **specific extension in this repository**. To file a feature request that affects multiple extensions or the Firebase Extensions platform, please reach out to
[Firebase support](https://firebase.google.com/support/troubleshooter/report/features/) directly.

### [REQUIRED] Step 2: Extension name

[speech-to-text](https://github.com/GoogleCloudPlatform/firebase-extensions/tree/next/speech-to-text)

### What feature would you like to see?

Add the original file that was processed for transcription. It makes it hard to relate the transcription text back to the file that was processed. Yes, I can grab the additional file that is in the storage bucket, but I would rather work with just the event arc transcription object than have to parse the output file.

### How would you use it?

I would use it to relate the transcription event to a particular file that was processed.

**Comment by nohe427** [comment] 2023-07-19 20:03
Here is the current JSON Payload that I am seeing:

```
"jsonPayload": {
    "data": {
      "transcription": {
        "0": [
          "some text",
          " some more text",
          " some more more text"
        ]
      },
      "status": 0,
      "warnings": []
    },
    "id": "${ANOTHER_GUID}",
    "source": "//firebaseextensions.googleapis.com/extensions/projects/${PROJECT_ID}/instances/speech-to-text",
    "specversion": "1.0",
    "traceparent": "${GUID}",
    "type": "firebase.extensions.storage-transcribe-audio.v1.complete"
  },
```

**Comment by cabljac** [comment] 2023-11-23 11:11
This is a duplicate of https://github.com/GoogleCloudPlatform/firebase-extensions/issues/68 

This should have been addressed in https://github.com/GoogleCloudPlatform/firebase-extensions/pull/94

**Closed by cabljac** 2023-11-23 11:11 UTC
Labels: type: feature request
